[build]
  functions = "api"

[[redirects]]
  from = "/api/notify"
  to = "/api/notify"
  status = 200

[[headers]]
  for = "/api/notify"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
